export const fox = {
  palette: {"G":[55,165,85],"R":[194,36,79],"B":[52,112,178],"F":[225,132,93],"L":[244,177,146]},
  glyphs: [
    "                        ⢀⡀⠄",
    "                    ⣀⢀⠔⠈⡠",
    "        ⢰⠠⢀⡀   ⢀⢠⠰ ⠂⠇⠁⡀⡐⠁⠒⠛⠁⢔⠠⡀⣀⠔⠆",
    "        ⠸⠈⠂⠠⠍⢉⡉⠉⠁⠒⠒⡠  ⢱ ⡁    ⠁⢊  ⡀",
    "         ⢣   ⡀⠈⠢⡀⢠⠊   ⢸⠠⠁⠂   ⠈⠢⡑⣀⢳",
    "         ⢈⠦ ⢸⠈⠐⠂⢾⠁    ⠌⠁ ⠘⡀    ⢡⠈⡄",
    "        ⢠⢣⠸⡁⠈⢀⣀⡀⡎       ⢀⡀⠈⠒⡀⠠⡀⠸ ⢰",
    "        ⡆⢸ ⠈⠐⠂  ⡦    ⠌  ⡼⣁  ⠁⡘⠡⠂ ⠿",
    "        ⣇⠄⢆     ⢠   ⢸⠰⠒⣚⣨⢜⢦⡀⠈  ⢀⠎⠇",
    "        ⠋⠸⡈⢦    ⡼⡄  ⢸ ⣑⢿⡠⢨⡿⡕⡀ ⢀⠌⢀⠘⠄",
    "          ⠱⡆⠱   ⢧⢹⢆  ⠔ ⠉⠉⠐⠒⢀⢇⠔⢚⡄⡇",
    "           ⠱ ⣅  ⠈⠃ ⠓⢤⣘⣄       ⣑⣃⣃⡀",
    "            ⠡⣇⡅⢆  ⢀ ⠱⣄⠈    ⠁⠒⠨⠊",
    "        ⠔⠉⠁⠙⠁⠤⢥⢈⢆ ⡼⢄⡀⠱⠉⠒⢤⠄⣀⡀",
    "      ⢠⠂      ⢀⠌ ⡵ ⠉⠪⠔⡃ ⡗⠒⠠⢄",
    "      ⠃     ⣀⠠⠤       ⠈⠢⡁ ⠉⠢⡀",
    "      ⡆ ⡀⠔⠊⠁            ⠈⢾⠄ ⠈⣆",
    "      ⠕⠁   ⡀⠄ ⢁⠔⠉ ⠉⠉⠐⠂⠤⣀  ⠙⠄⢠⠇⡣",
    "      ⢂  ⢀⠊  ⢠⠁   ⠐⠠⡀   ⡍⠒⠠⣌⢿⡰⡁",
    "      ⠰⢀⢀⠂   ⢸      ⠈⢊⠄ ⢰  ⠈⠫⡘⣡",
  ],
  colors: [
    "                        FFF",
    "                    FFFFF",
    "        FFFF   FFF FFFFFFFFFFFFFFF",
    "        FFFFFFFFFFFF  F F    LF  F",
    "         F   LLLFFF   FFFF   LLLFF",
    "         FF LLLLLF    FF FF    LLF",
    "        FFFLLLLLL       FFFFFLLL L",
    "        FF LLL  F    F  FF  LLLL F",
    "        FFF     F   LFGGGGGFL  LFF",
    "        FFFF    FF  L LGGGGGF LLFLL",
    "          FFL   FFF  L LLLFLLLLFF",
    "           F L  LL LFLF       LFLF",
    "            FFFL  L LFF    LLLL",
    "        RRRRRRRLF LFLLFFFFLL",
    "      FR      RR R RRRF FFLF",
    "      R     RRR       RRF LFF",
    "      R RRRR            RRF FF",
    "      RR   RR RRB BBBBRR  RRFFR",
    "      R  RR  RB   BBB   BBBRRRR",
    "      FRRR   R      BBB B  BBBB",
  ],
} as const;
